[package]
name = "golem-schema-lift"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
macros = {path = "../macros"}
golem-rust = {workspace = true}

[[test]]
name = "agent"
path = "tests/agent.rs"
