[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

proc-macro = true

[dependencies]
golem-rust = {workspace = true}
proc-macro-crate = "3.4.0"
proc-macro2 = "1"
quote = "1"
syn = {version = "2", features = ["extra-traits", "full", "fold", "parsing"]}